services:
  neo4j:
    image: neo4j:5.9.0-community
    container_name: phi-neo4j
    user: "${UID:-501}:${GID:-20}"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
      - ./import:/import
    environment:
      - NEO4J_AUTH=neo4j/phi-neo4j
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    command:
      - --apoc.export.file.enabled=true
      - --apoc.import.file.enabled=true
      - --apoc.import.file.use_neo4j_config=true
    entrypoint: 
      - "/startup/docker-entrypoint.sh"
      - "neo4j"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: phi-neo4j